### ISSUE TITLE
Check responsivity

### ISSUE THREAD

**Issue by Riserax** [Riserax/food-hub#31]

**Comment by WeruSSia** [comment]
![image](https://user-images.githubusercontent.com/37249143/80822251-98264e00-8bda-11ea-9a54-79d082574f74.png)
Recipe card without image is acting strangely when screen size decreases.

**Comment by konrad-adamik** [comment]
![image](https://user-images.githubusercontent.com/19648783/80825441-b1ca9400-8be0-11ea-8cdd-38f3e744afb8.png)

Snackbar is not centered when width is lower.
